using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using QiaKon.Contracts;

namespace QiaKon.Shared;

internal sealed class DocumentGraphProjectionService
{
    private static readonly Regex MarkdownHeadingRegex = new(@"^(#{1,6})\s+(?<title>.+?)\s*$", RegexOptions.Compiled | RegexOptions.Multiline);

    private readonly QiaKonAppDbContext _dbContext;

    public DocumentGraphProjectionService(QiaKonAppDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public async Task SyncDocumentAsync(
        DocumentRow document,
        IReadOnlyList<DocumentChunkRow> chunkRows,
        CancellationToken cancellationToken = default)
    {
        await DeleteDocumentGraphAsync(document.Id, cancellationToken);

        var now = DateTime.UtcNow;
        var documentEntityId = GetDocumentEntityId(document.Id);
        var entities = new List<GraphEntityRow>
        {
            CreateEntity(
                documentEntityId,
                string.IsNullOrWhiteSpace(document.Title) ? $"文档 {document.Id:N}" : document.Title,
                "文档",
                document,
                new JsonObject
                {
                    ["autoGenerated"] = true,
                    ["nodeKind"] = "document",
                    ["sourceDocumentId"] = document.Id.ToString(),
                    ["sourceDocumentTitle"] = document.Title,
                    ["documentType"] = document.Type.ToString(),
                    ["chunkCount"] = chunkRows.Count,
                },
                now)
        };

        var relations = new List<GraphRelationRow>();
        var headings = ExtractHeadings(document.Content).Take(24).ToList();
        if (headings.Count >= 2)
        {
            BuildHeadingGraph(document, now, documentEntityId, headings, entities, relations);
        }
        else
        {
            BuildChunkGraph(document, now, documentEntityId, chunkRows.Take(8).ToList(), entities, relations);
        }

        if (relations.Count > 0)
        {
            _dbContext.GraphRelations.AddRange(relations);
        }

        _dbContext.GraphEntities.AddRange(entities);
        await _dbContext.SaveChangesAsync(cancellationToken);
    }

    public async Task DeleteDocumentGraphAsync(Guid documentId, CancellationToken cancellationToken = default)
    {
        var prefix = GetDocumentPrefix(documentId);

        var relations = await _dbContext.GraphRelations
            .Where(x => EF.Functions.Like(x.Id, prefix + "%"))
            .ToListAsync(cancellationToken);
        if (relations.Count > 0)
        {
            _dbContext.GraphRelations.RemoveRange(relations);
        }

        var entities = await _dbContext.GraphEntities
            .Where(x => EF.Functions.Like(x.Id, prefix + "%"))
            .ToListAsync(cancellationToken);
        if (entities.Count > 0)
        {
            _dbContext.GraphEntities.RemoveRange(entities);
        }

        if (relations.Count > 0 || entities.Count > 0)
        {
            await _dbContext.SaveChangesAsync(cancellationToken);
        }
    }

    private static void BuildHeadingGraph(
        DocumentRow document,
        DateTime now,
        string documentEntityId,
        IReadOnlyList<HeadingDescriptor> headings,
        List<GraphEntityRow> entities,
        List<GraphRelationRow> relations)
    {
        var stack = new Stack<HeadingNode>();
        foreach (var heading in headings)
        {
            var sectionId = $"{GetDocumentPrefix(document.Id)}section_{heading.Order:D3}";
            entities.Add(CreateEntity(
                sectionId,
                heading.Title,
                "章节",
                document,
                new JsonObject
                {
                    ["autoGenerated"] = true,
                    ["nodeKind"] = "section",
                    ["sourceDocumentId"] = document.Id.ToString(),
                    ["sourceDocumentTitle"] = document.Title,
                    ["headingLevel"] = heading.Level,
                    ["order"] = heading.Order,
                },
                now));

            while (stack.Count > 0 && stack.Peek().Level >= heading.Level)
            {
                stack.Pop();
            }

            if (stack.Count == 0)
            {
                relations.Add(CreateRelation(
                    $"{GetDocumentPrefix(document.Id)}contains_section_{heading.Order:D3}",
                    documentEntityId,
                    sectionId,
                    "包含",
                    document,
                    new JsonObject
                    {
                        ["autoGenerated"] = true,
                        ["sourceDocumentId"] = document.Id.ToString(),
                        ["order"] = heading.Order,
                    },
                    now));
            }
            else
            {
                relations.Add(CreateRelation(
                    $"{GetDocumentPrefix(document.Id)}section_parent_{stack.Peek().Order:D3}_{heading.Order:D3}",
                    stack.Peek().Id,
                    sectionId,
                    "子章节",
                    document,
                    new JsonObject
                    {
                        ["autoGenerated"] = true,
                        ["sourceDocumentId"] = document.Id.ToString(),
                        ["parentOrder"] = stack.Peek().Order,
                        ["order"] = heading.Order,
                    },
                    now));
            }

            stack.Push(new HeadingNode(sectionId, heading.Level, heading.Order));
        }
    }

    private static void BuildChunkGraph(
        DocumentRow document,
        DateTime now,
        string documentEntityId,
        IReadOnlyList<DocumentChunkRow> chunkRows,
        List<GraphEntityRow> entities,
        List<GraphRelationRow> relations)
    {
        GraphEntityRow? previousChunk = null;
        foreach (var chunk in chunkRows)
        {
            var chunkEntityId = $"{GetDocumentPrefix(document.Id)}chunk_{chunk.Order:D3}";
            var chunkEntity = CreateEntity(
                chunkEntityId,
                BuildChunkName(chunk),
                "片段",
                document,
                new JsonObject
                {
                    ["autoGenerated"] = true,
                    ["nodeKind"] = "chunk",
                    ["sourceDocumentId"] = document.Id.ToString(),
                    ["sourceDocumentTitle"] = document.Title,
                    ["chunkId"] = chunk.Id.ToString(),
                    ["order"] = chunk.Order,
                    ["chunkingStrategy"] = chunk.ChunkingStrategy,
                    ["snippet"] = TruncateText(chunk.Content, 160),
                },
                now);

            entities.Add(chunkEntity);
            relations.Add(CreateRelation(
                $"{GetDocumentPrefix(document.Id)}contains_chunk_{chunk.Order:D3}",
                documentEntityId,
                chunkEntityId,
                "包含",
                document,
                new JsonObject
                {
                    ["autoGenerated"] = true,
                    ["sourceDocumentId"] = document.Id.ToString(),
                    ["order"] = chunk.Order,
                },
                now));

            if (previousChunk is not null)
            {
                relations.Add(CreateRelation(
                    $"{GetDocumentPrefix(document.Id)}next_chunk_{chunk.Order - 1:D3}_{chunk.Order:D3}",
                    previousChunk.Id,
                    chunkEntityId,
                    "下一段",
                    document,
                    new JsonObject
                    {
                        ["autoGenerated"] = true,
                        ["sourceDocumentId"] = document.Id.ToString(),
                        ["fromOrder"] = chunk.Order - 1,
                        ["toOrder"] = chunk.Order,
                    },
                    now));
            }

            previousChunk = chunkEntity;
        }
    }

    private static GraphEntityRow CreateEntity(
        string id,
        string name,
        string type,
        DocumentRow document,
        JsonObject properties,
        DateTime now)
        => new()
        {
            Id = id,
            Name = name,
            Type = type,
            DepartmentId = document.DepartmentId,
            IsPublic = document.AccessLevel == AccessLevel.Public,
            PropertiesJson = PostgresDocumentService.SerializeJson(properties),
            CreatedBy = document.CreatedBy,
            CreatedAt = now,
            UpdatedAt = now,
        };

    private static GraphRelationRow CreateRelation(
        string id,
        string sourceId,
        string targetId,
        string type,
        DocumentRow document,
        JsonObject properties,
        DateTime now)
        => new()
        {
            Id = id,
            SourceId = sourceId,
            TargetId = targetId,
            Type = type,
            DepartmentId = document.DepartmentId,
            PropertiesJson = PostgresDocumentService.SerializeJson(properties),
            CreatedBy = document.CreatedBy,
            CreatedAt = now,
        };

    private static IReadOnlyList<HeadingDescriptor> ExtractHeadings(string? content)
    {
        if (string.IsNullOrWhiteSpace(content))
        {
            return Array.Empty<HeadingDescriptor>();
        }

        var matches = MarkdownHeadingRegex.Matches(content);
        var headings = new List<HeadingDescriptor>(matches.Count);
        var order = 1;
        foreach (Match match in matches)
        {
            var title = match.Groups["title"].Value.Trim();
            if (string.IsNullOrWhiteSpace(title))
            {
                continue;
            }

            headings.Add(new HeadingDescriptor(order++, match.Groups[1].Value.Length, title));
        }

        return headings;
    }

    private static string BuildChunkName(DocumentChunkRow chunk)
    {
        var text = chunk.Content.Replace("\r", " ").Replace("\n", " ").Trim();
        return string.IsNullOrWhiteSpace(text)
            ? $"片段 #{chunk.Order}"
            : $"片段 #{chunk.Order}: {TruncateText(text, 28)}";
    }

    private static string TruncateText(string text, int maxLength)
        => text.Length <= maxLength ? text : text[..(maxLength - 3)] + "...";

    private static string GetDocumentEntityId(Guid documentId)
        => GetDocumentPrefix(documentId).TrimEnd('_');

    private static string GetDocumentPrefix(Guid documentId)
        => $"auto_doc_{documentId:N}_";

    private sealed record HeadingDescriptor(int Order, int Level, string Title);

    private sealed record HeadingNode(string Id, int Level, int Order);
}